import Link from "next/link"
import "./globals.css"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
import { ModeToggle } from "@/components/mode-toggle"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Header is contained */}
          <header className="max-w-2xl px-4 py-10 mx-auto">
            <div className="flex items-center justify-between">
              <ModeToggle />
              <nav className="ml-auto space-x-6 text-sm font-medium">
                <Link href="/">Home</Link>
                <Link href="/about">About</Link>
              </nav>
            </div>
          </header>

          {/* Main layout is full-width, children control their max-width */}
          <main>{children}</main>

          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}